## You should change each of the following fields
## to customize your blog

title: EDA basics in Data Science
description: "Learning what EDA is, and how to get starte using it." 
author: Rylan Van Komen
author_description: "BYU Student learning about Data Science" 

url: https://rvk23.github.io
baseurl: https://github.com/rvk23/my-blog 
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  rvk23
    twitter: 
    facebook: 
    email: 
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




